Traceback (most recent call last):
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
_, ax = plt.subplots()
init_prices = [4, 6.6, 8]
init_pe = 6
T = 10

for p0 in init_prices:
    prices = simulate(m, p0, init_pe, T)
    ax.plot(prices, label=rf'$p_0 = {p0}$')

ax.set_xlabel(r'æ—¶é—´$t$', fontsize=12)
ax.set_ylabel(r'ä»·æ ¼$p_t$', fontsize=12)
ax.legend()
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[15], line 7[0m
[1;32m      4[0m T [38;5;241m=[39m [38;5;241m10[39m
[1;32m      6[0m [38;5;28;01mfor[39;00m p0 [38;5;129;01min[39;00m init_prices:
[0;32m----> 7[0m     prices [38;5;241m=[39m [43msimulate[49m(m, p0, init_pe, T)
[1;32m      8[0m     ax[38;5;241m.[39mplot(prices, label[38;5;241m=[39m[38;5;124mrf[39m[38;5;124m'[39m[38;5;124m$p_0 = [39m[38;5;132;01m{[39;00mp0[38;5;132;01m}[39;00m[38;5;124m$[39m[38;5;124m'[39m)
[1;32m     10[0m ax[38;5;241m.[39mset_xlabel([38;5;124mr[39m[38;5;124m'[39m[38;5;124mæ—¶é—´$t$[39m[38;5;124m'[39m, fontsize[38;5;241m=[39m[38;5;241m12[39m)

[0;31mNameError[0m: name 'simulate' is not defined
NameError: name 'simulate' is not defined

