Traceback (most recent call last):
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/humphrey/anaconda3/envs/quantecon/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# 测量自定代码版本的时间
P = np.array([[0.8, 0.2], [0.1, 0.9]])
ψ_0 = [0.5, 0.5]

custom_code_time = measure_custom_code(P, ψ_0)
qe_code_time = measure_qe_code(P)

print(f"自定代码时间: {custom_code_time:.6f} 秒")
print(f"QuantEcon 代码时间: {qe_code_time:.6f} 秒")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[17], line 5[0m
[1;32m      2[0m P [38;5;241m=[39m np[38;5;241m.[39marray([[[38;5;241m0.8[39m, [38;5;241m0.2[39m], [[38;5;241m0.1[39m, [38;5;241m0.9[39m]])
[1;32m      3[0m ψ_0 [38;5;241m=[39m [[38;5;241m0.5[39m, [38;5;241m0.5[39m]
[0;32m----> 5[0m custom_code_time [38;5;241m=[39m [43mmeasure_custom_code[49m(P, ψ_0)
[1;32m      6[0m qe_code_time [38;5;241m=[39m measure_qe_code(P)
[1;32m      8[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124m自定代码时间: [39m[38;5;132;01m{[39;00mcustom_code_time[38;5;132;01m:[39;00m[38;5;124m.6f[39m[38;5;132;01m}[39;00m[38;5;124m 秒[39m[38;5;124m"[39m)

[0;31mNameError[0m: name 'measure_custom_code' is not defined
NameError: name 'measure_custom_code' is not defined

